apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakerapp
spec:
  selector:
      matchLabels:
        app: fakerapp
  replicas: 3
  template:
      metadata:
        labels:
            app: fakerapp
      spec:
        containers:
        - name: fakerapp
          image: bf4046/fakerapp:v2
          imagePullPolicy: Always
          # readinessProbe:
          #   httpGet:
          #     port: 8000
          #     path: /
          # livenessProbe:
          #   httpGet:
          #     port: 8000
          #     path: /
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
